# .github/workflows/process-hrv.yml
name: Process Oura HRV Data

on:
  # Webhook trigger via repository_dispatch
  repository_dispatch:
    types: [oura-data-updated]
  
  # Daily trigger at 9:45 AM Chicago time
  # Chicago is UTC-6 (CST) or UTC-5 (CDT), so 9:45 AM Chicago = 14:45 UTC (CDT) or 15:45 UTC (CST)
  # Using 14:45 UTC for Daylight Saving Time (March-November)
  schedule:
    - cron: '*/20 10,11,12,13,14 * * *'  # run every 20 minutes in the morning (5 CDT - 9:45 CDT)
    - cron: '0 16,17,18,19,20 * * *' # rerun on the hour starting at 11 am CDT
  
  # Manual trigger for testing
  workflow_dispatch:

jobs:
  process-hrv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Process HRV data
      env:
        OURA_CLIENT_ID: ${{ secrets.OURA_CLIENT_ID }}
        OURA_CLIENT_SECRET: ${{ secrets.OURA_CLIENT_SECRET }}
        OURA_REFRESH_TOKEN: ${{ secrets.OURA_REFRESH_TOKEN }}
        REPO_SECRETS_TOKEN: ${{ secrets.REPO_SECRETS_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        mkdir -p data
        python src/main.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check both possible locations for JSON files
        if ls data/*.json 1> /dev/null 2>&1; then
          echo "Found JSON files in data/"
          git add data/*.json
        elif ls src/data/*.json 1> /dev/null 2>&1; then
          echo "Found JSON files in src/data/, moving to data/"
          mkdir -p data
          mv src/data/*.json data/
          git add data/*.json
        else
          echo "ℹ️ No HRV data files found to commit"
          exit 0
        fi
        
        git diff --staged --quiet || git commit -m "Update HRV data - $(date -u +"%Y-%m-%d %H:%M UTC")"
        git push
        echo "✅ HRV data files committed and pushed"
    
    - name: Log completion
      run: |
        echo "HRV processing completed at $(date -u)"
        ls -la data/